export const AUTH_STRINGS = {
    login: {
        title: 'Welcome Back',
        subtitle: 'Sign in to continue learning',
        formTitle: 'Login',
        formSubtitle: 'Use your FreeAPI account credentials.',
        usernameLabel: 'Username',
        usernamePlaceholder: 'Enter your username',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Enter your password',
        submit: 'Login',
        switchPrompt: "Don't have an account? ",
        switchAction: 'Sign Up',
    },
    register: {
        title: 'Create Account',
        subtitle: 'Start your learning journey today',
        formTitle: 'Sign Up',
        formSubtitle: 'Create your secure learning profile.',
        usernameLabel: 'Username',
        usernamePlaceholder: 'Choose a username',
        emailLabel: 'Email',
        emailPlaceholder: 'Enter your email',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Create a password',
        confirmPasswordLabel: 'Confirm Password',
        confirmPasswordPlaceholder: 'Confirm your password',
        submit: 'Create Account',
        switchPrompt: 'Already have an account? ',
        switchAction: 'Login',
    },
    alerts: {
        loginFailedTitle: 'Login Failed',
        loginFailedFallback: 'Unable to login. Please try again.',
        invalidCredentials: 'Invalid credentials',
        registrationFailedTitle: 'Registration Failed',
        registrationFailedFallback: 'Unable to create account. Please try again.',
        registrationFailedShort: 'Unable to create account',
        registrationSuccessTitle: 'Success!',
        registrationSuccessMessage: 'Your account has been created successfully.',
        ok: 'OK',
    },
} as const;
